CrimeWatch/Controllers/HomeController.cs
using CrimeWatch.Models;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using System;
using System.Web;
using System.Globalization;
using System.Web.Security;

namespace CrimeWatch.Controllers
{
    public class HomeController : Controller
    {
        private readonly CrimeWatchModel _db = new CrimeWatchModel();


        /// <summary>
        /// Redirects to the home page.
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            return View();
        }

        public void AddUserToRole()
        {
            Roles.CreateRole("Administrator");   
            
            Roles.AddUserToRole("admin@admin.com", "Administrator");

        }

        /// <summary>
        /// Redirects to user portal View (Dashboard).
        /// </summary>
        /// <returns>The Id of logged in user</returns>
        public ActionResult MyPortal()
        {
            return View(_db.AspNetUsers.Find(User.Identity.GetUserId()));
        }
    }
}

CrimeWatch/Controllers/MapController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using CrimeWatch.Services;
using PoliceUk.Entities.StreetLevel;

namespace CrimeWatch.Controllers
{
    public class MapController : Controller
    {
        private readonly CommonFunctions _cf = new CommonFunctions();
        private readonly MapService service = new MapService();

        /// <summary>
        /// Redirects to Map Parameters View
        /// </summary>
        /// <returns></returns>
        public ActionResult Parameters()
        {     
            //Passes the dates and crime categories dropdowns to View
            ViewBag.dateDD = _cf.ReturnDateDd();
            ViewBag.typeDD = _cf.ReturnTypeDd();
            return View();
        }

        /// <summary>
        /// Redirects to Map View. Passes all neccessary elements via ViewBag
        /// </summary>
        /// <param name="address"></param>
        /// <param name="date"></param>
        /// <param name="type"></param>
        /// <returns></returns>
        public ActionResult Map(string address, string date, string type) {
            //Passes dates dropdown
            ViewBag.dateDD = _cf.ReturnDateDd();
            //Passes crime categories dropdown
            ViewBag.typeDD = _cf.ReturnTypeDd();
            //Passes dates dropdown
            ViewBag.type = type;
            ViewBag.date = date;
            ViewBag.address = address;            
            List<Crime> crimes = service.Map(address, date, type);
            var latLng = service.ReturnLatLng(address);
            ViewBag.lat = float.Parse(latLng.First().Value);
            ViewBag.lng = float.Parse(latLng.ElementAt(1).Value);

            return View(crimes);
        }
    }
}

CrimeWatch/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model List<CrimeWatch.Models.PoliceDepartment>
<body onload="startTimer()">
    <br /><br />
    <br /><br />

    <div class="container" id="homeMainCont">
        <div class="col-lg-6">
            <img src="~/Content/Images/img1.png" id="img1" class="homepageImage" />
            <br /><br />
            <form style="margin-left:50%">
                <input name="field" type="radio" id="radioBtn1" class="radioBtn">
                <input name="field" type="radio" id="radioBtn2" class="radioBtn">
                <input name="field" type="radio" id="radioBtn3" class="radioBtn">
            </form>
        </div>
        <div class="col-lg-6">
            <div class="container" style="width:420px;">
                <img id="logo" src="~/Content/Images/logo.png" />
                <div class="container homeDescription">
                    CrimeWatch allows you to explore the current and future criminality rates of your neighbourhood or greater area using interactive features and accurate prediction models.
                    @if (!Request.IsAuthenticated)
                    { 
                    <br /><br />
                    <p class="homeDescription"><a href="#" onclick="location.href='@Url.Action("Login", "Account")'">Log in</a> to get started.</p>
                    }
                </div>               
            </div>
        </div>
    </div>

    <div class="row infoCont" id="one">
        <div class="col-lg-6">
            <h2>What is CrimeWatch?</h2>
            <br />
            <h4>
                It is a web application that aims to provide in-depth information about criminality in the UK and Wales. To achieve that, CrimeWatch has adopted a list of interactive data presentation tools. These include: <br /><br /><b>- Interactive crime map<br />- Graphs and charts<br />- Statistic crime tables</b><br /><br /> CrimeWatch is also capable making estimations for future crime numbers. By implementing a <b>multiple linear regression model</b>, it can accurately forecast the number of total crimes and crimes by type for a selected region.
            </h4>
            <br /><br />
        </div>
        <div class="col-lg-6">
            <img id="img2" src="~/Content/Images/img1.png" class="homepageImage" />
            <br /><br />
            <form class="centeredText">
                <input name="field" type="radio" id="radioBtn4" class="radioBtn">
                <input name="field" type="radio" id="radioBtn5" class="radioBtn">
                <input name="field" type="radio" id="radioBtn6" class="radioBtn">
            </form>
        </div>
    </div>

    <div class="row infoCont" id="two">
        <div class="col-lg-6">
            <h2>How does it work ?</h2>
            <div style="overflow-y:scroll; height:280px">
                <h4>
                    <b>Data Source</b><br />Crimewatch is based on crime reports (Excel files) published by the UK Police on a monthly basis. The application loops through these files and extracts and stores all crime information. It afterwards manipulates them to the point they reveal useful information about criminality in an area.<br /><br /> <b>Maps and charts</b><br />Police data reveal the latitute and longitude attributes of each crime making it possible for CrimeWatch to visualise the exact location of a crime by using an interactive map. On the other hand, the charts present an aggregated view of the data reveiling criminaity figures for each of the regions in the UK and Wales.<br><br /><b>Machine Learning</b><br>CrimeWatch has the ability to forecast the total number of crimes that are going to occur in an area. To achieve that, the application implements a multiple linear regression model with itegration of the Statistical language R.
                </h4>
            </div>
            <br /><br />
        </div>
        <div class="col-lg-6">
            <img id="img3" src="~/Content/Images/map.png" class="homepageImage" />
            <br /><br />
            <form class="centeredText">
                <input name="field" type="radio" id="radioBtn7" class="radioBtn">
                <input name="field" type="radio" id="radioBtn8" class="radioBtn">
                <input name="field" type="radio" id="radioBtn9" class="radioBtn">
            </form>
        </div>
    </div>

    <div id='footer'>
        <br />
        <address>
            24A Guildford Park road<br />
            Guildford, United Kingdom, GU2 7ND<br />
            <strong>Tel:</strong> <a href="#">+44 7482868848</a><br />
            <strong>Email:</strong> <a href="mailto:support@crimewatch.com">Support@example.com</a><br />
        </address>
    </div>
</body>

CrimeWatch/Views/Home/MyPortal.cshtml
@model CrimeWatch.Models.AspNetUser
@{
    ViewBag.Title = "User Portal";
    Layout = "~/Views/Shared/_LayoutPortal.cshtml";
}

<div class="row">
    @if (Model.EmailConfirmed)
    {
        <div class="col-lg-9">
            <br />
            <div class="container customCont centeredText" style="width:85%;">
                <h3 class="title">User Portal</h3>
                <br />
                <div class="row">
                    <button class="menuBtn" onclick="location.href='@Url.Action("Parameters", "Map")'">Crimes Map<br /><span class="glyphicon glyphicon-map-marker portalGlyph"></span></button>
                    <button class="menuBtn" onclick="location.href='@Url.Action("Parameters", "Graphs")'">Graphs<br /><span class="glyphicon glyphicon-stats portalGlyph"></span></button>
                    <button class="menuBtn" onclick="location.href='@Url.Action("Stats", "Stats", new { period = 1 })'">Statistics<br /><span class="glyphicon glyphicon-list-alt portalGlyph"></span></button>
                </div>
                <hr />
                <div class="row">
                    <button class="menuBtn" onclick="location.href='@Url.Action("Clusters", "Clustering")'">Counties Clusters<br /><span class="glyphicon glyphicon-adjust portalGlyph"></span></button>
                    <button class="menuBtn" onclick="location.href='@Url.Action("Prediction", "Regression", new{ countyName="", dateStr="" })'">Crime Estimations<br /><span class="glyphicon glyphicon-random portalGlyph"></span></button>
                    <button class="menuBtn" onclick="location.href='https://data.police.uk/'" target="_blank">Police Dataset<br /><span class="glyphicon glyphicon-info-sign portalGlyph"></span></button>
                    <br /><br /><br />
                </div>
            </div>
        </div>
    }
    else
    {
        <div class="col-lg-9">
            <div id="notVerifiedMsg" class="container">
                <br />
                <h3 class="title">Your account is not verified</h3>
                <br />
                <h4>This page requires your account to be verified. Please verify your acocunt by clicking the link sent to the email address you provided.</h4>
                <h3 class="title">Didn't receive an email ?</h3>
                <br />
                <h4>1) Did you make a mistake when typing your email ? You can check your details on the top right of the page. If this is the case, you must change your email by pressing 'Change login details'. Then, you should resend the confirmation email to the correct address by pressing the 'Send confirmation email' button.</h4>
                <h4>2) Did you wait long enough ? Sometimes it takes up to few minutes to receive the confirmation email. Please wait for 3 to 4 minutes if you haven't done so.</h4>
                <br />
                <h4 class="inline">If none of the above applies:</h4>
                <button id="sendConfirmationEmailBtn" type="button" class="btn btn-lg btn-warning" onclick="location.href='@Url.Action("SendConfirmationEmail", "Account")'">Send confirmation email</button>
                <br /><br />
            </div>
        </div>
    }
    <br />
    <div class="col-lg-3 customCont">
        <br />
        <h3 class="title">My Details <span class="glyphicon glyphicon-user"></span></h3>
        <br />
        <ul class="list-group">
            <li class="list-group-item userDetails"><strong>Full Name: </strong> @Model.FullName</li>
            <li class="list-group-item userDetails"><strong>Phone Number: </strong> @Model.PhoneNumber</li>
            <li class="list-group-item userDetails" style="padding-bottom:35px;"><strong>Email: </strong> @Model.Email</li>
            <hr />
            <li class="list-group-item portalLink">
                @Html.ActionLink("Change Contact Details", "ChangeContactDetails", "Account", null, new { @class = "blackTxt" })
            </li>
            <li class="list-group-item portalLink">
                @Html.ActionLink("Change Login Details", "ChangeLoginDetails", "Account", null, new { @class = "blackTxt" })
            </li>
            <li class="list-group-item portalLink">
                @using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm" }))
                {
                    @Html.AntiForgeryToken()
                    <a href="javascript:javascript:document.getElementById('logoutForm').submit()" class="blackTxt">Log Out</a>
                }
            </li>
            <li class="list-group-item portalLink deleteAccountLink"><a class="blackTxt" onclick="return confirm('Are you sure you want to delete your account?');" href="@Url.Action("DeleteUser", "Account", new { email = User.Identity.Name })">Delete Account</a></li>
        </ul>
    </div>
</div>